### ISSUE TITLE
Remote trace option in studio

### ISSUE THREAD

**Issue by praveen4565** [SpringRoll/SpringRollStudio#6]
Can I have more information on Remote trace option in studio?. If this helps to do the remote debugging? can you please explain the steps to do it?

**Comment by bigtimebuddy** [comment]
In general, Safari on iOS and Google Chrome on Android support debugging methods over USB. You can find lots of information about this online. But there are some cases where it's helpful to have another options for debugging, so we added Remote Trace to SpringRoll Studio.

Here is the basic requirements:
* Make sure "components/springroll/dist/modules/debug.js" and "components/springroll/dist/modules/debug.css" are included in **springroll.json** in the `librariesDebug` section.
* Build your application and libraries in debug mode (e.g. `grunt debug`).
* Enable the `debugRemote` option on your application, see [docs](http://springroll.github.io/SpringRoll/docs/classes/springroll.Application.html#property_options.debugRemote).

```
// debugRemote can be IP or host name where to send logs
// should be the computer on the network which is running
// SpringRoll Studio with the Remote window opened. 
var app = new Application({
	debugRemote: '10.1.10.1' 
});
```
Then, in order to send messages to the Remote Trace window in SpringRoll Studio, you simply use the Debug class in SpringRoll. Debug works just like console. Full API is [here](http://springroll.github.io/SpringRoll/docs/classes/springroll.Debug.html).

```js
var Debug = include('springroll.Debug');
Debug.log("General message");
Debug.warn("Warning message");
Debug.green("Colored Green!"); // support for colors
Debug.log({ value: 100 }); // support for objects
```
